Add support for Walleys Part Payment widget
krokedil/collector-checkout-for-woocommerce pull request #209
Opened 2023-11-22 10:19 UTC by MichaelBengtsson

* Feature - Adds support for Walley Part Payment Widget on the cart and product pages in WooCommerce.

2023-11-22 10:19 UTC, MichaelBengtsson commented
Task linked: [CU-86934uary Create package for (and add support for) Walley Part Payment Widget](https://app.clickup.com/t/86934uary)

2023-12-07 08:15 UTC, NiklasHogefjord requested changes

2023-12-07 08:15 UTC, NiklasHogefjord commented on classes/class-walley-checkout-assets.php
> +	public function register_widget_assets() {
It looks as these files are enqueued on all pages. Should we include a check so they only are enqueued on product pages if activated in settings?

2023-12-07 08:15 UTC, NiklasHogefjord commented on collector-checkout-for-woocommerce.php
> +			include_once COLLECTOR_BANK_PLUGIN_DIR . '/classes/class-walley-part-payment-widget.php';
What happens if the old checkout API is used? Will it still display the part payment widget settings?

2023-12-07 10:44 UTC, MichaelBengtsson commented on classes/class-walley-checkout-assets.php
> +	public function register_widget_assets() {
This part of the code only registers the assets. They are not enqueued here.

That is done in the package for the widgets themselves. The Cart and Product widgets both have a method that's called `is_valid_page` where they check for `is_cart` and `is_product` respectively.
Before we enqueue the scripts we check against this method and if the widget itself is enabled by using the setting. We only register the scripts this early to ensure they are available when the package needs to enqueue them.

We pass the handles to the Cart and Product widget classes when we register them in the [Walley_Part_Payment_Widget class](https://github.com/krokedil/collector-checkout-for-woocommerce/blob/develop-part-payment-widget/classes/class-walley-part-payment-widget.php#L58-L74). These handles are then enqueued when the classes for the widgets notice that the widget should be used.

I cant see that the scripts or style are enqueued on any other page then what they are intended for in my testing.

2023-12-07 11:09 UTC, MichaelBengtsson commented on collector-checkout-for-woocommerce.php
> +			include_once COLLECTOR_BANK_PLUGIN_DIR . '/classes/class-walley-part-payment-widget.php';
Yes that is correct. Ill fix that and commit a change to only include the file and initiate the class when using the new api

2023-12-07 12:52 UTC, merged