Add compatibility with WooCommerce's HPOS
krokedil/collector-checkout-for-woocommerce pull request #219
Opened 2024-04-22 11:08 UTC by mntzrr

As described in the [recipe book](https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book):
- `get_post( $post_id )` → `wc_get_order( $post_id )`
- `update_post_meta` → `WC_Order::update_meta_data`
- `add_post_meta` → `WC_Order::add_meta_data`
- `delete_post_meta` → `WC_Order::delete_meta_data`

Furthermore, where applicable, if a method is available for the meta field, that will be used in favor of retrieving it through the meta data function.  For example,  

```
get_post_meta($order_id, '_transaction_id', true)
```
is replaced with 
```
WC_Order::get_transaction_id()
```

If a meta data function is available, and `update_meta_data` is still used, WooCommerce will warn about directly modifying internal meta data.

Note:
1. The HPOS-related methods _must_ be followed at some point by a `save()` call.
2. The recipe book does not seem to reference a replacement for `get_post_meta`, but this should be replaced by `WC_Order::get_meta`.

**If approved, please squash and merge.**

2024-05-17 06:36 UTC, MichaelBengtsson requested changes

2024-05-17 06:36 UTC, MichaelBengtsson commented on classes/class-walley-part-payment-widget.php
> +		$product = wc_get_product( walley_get_the_ID() );
I dont think you should use the walley_get_the_ID function here right? Since it should only get a order id, not a product id. And HPOS isnt used for products as far as i know, only order data. Was this tested?

2024-05-17 06:36 UTC, MichaelBengtsson commented on classes/requests/helpers/class-collector-checkout-requests-cart.php
> +		$part_number = ! empty( $product->get_sku() ) ? $product->get_sku() : $part_number = $product->get_id();
This dosent look right.

First of all it has a extra `)` after the `! empty(...)` statement. And second you in the else part of the ternary operation assign the value to `$part_number` again which isnt needed.  If you want to keep this as a ternary operation then change it to `! empty( $product->get_sku() ? $product->get_sku() : $product->get_id();`

The current code right now should result in a fatal error. I'm not sure how this didn't break in testing.

2024-05-17 06:36 UTC, MichaelBengtsson commented on classes/requests/helpers/class-walley-checkout-requests-fees-helper.php
> +		$part_number = ! empty( $product->get_sku() ) ? $product->get_sku() : $part_number = $product->get_id();
Same issue as the same method in the cart helper class. Is this code ever used though? Since its in the fee helper class, but looks to be for getting a product SKU. I cant see any reference to it in the code anywhere either.

2024-05-17 06:36 UTC, MichaelBengtsson commented on classes/requests/manage-orders/post/class-walley-checkout-request-cancel-order.php
> +		$order = wc_get_order($this->order_id);
PHPCS, space between parenthesis and the argument needed.

2024-05-17 06:36 UTC, MichaelBengtsson commented on classes/requests/manage-orders/post/class-walley-checkout-request-capture-order.php
> +		$order = wc_get_order($this->order_id);
PHPCS, space between parenthesis and the argument needed.

2024-05-17 06:36 UTC, MichaelBengtsson commented on classes/requests/manage-orders/post/class-walley-checkout-request-part-capture-order.php
> +		$order = wc_get_order($this->order_id);
PHPCS, space between parenthesis and the argument needed.

2024-05-17 06:36 UTC, MichaelBengtsson commented on classes/requests/soap/class-collector-checkout-soap-requests-credit-payment.php
> +		$order = wc_get_order($order_id);
PHPCS, space between parenthesis and the argument needed.

2024-06-04 14:45 UTC, mntzrr commented on classes/class-walley-part-payment-widget.php
> +		$product = wc_get_product( walley_get_the_ID() );
You're correct, it doesn't use HPOS, but I used `walley_get_the_ID` for the sake of consistency, as it is completely backwards-compatible with `get_the_ID`, thus no difference in functionality.

`get_the_ID` is not limited to orders. It also works on any post page, such as product pages. The original code was already using this, so I didn't change the logic. I have also verified with xdebug that I am receiving the expected product.

2024-06-04 14:55 UTC, mntzrr commented on classes/requests/helpers/class-collector-checkout-requests-cart.php
> +		$part_number = ! empty( $product->get_sku() ) ? $product->get_sku() : $part_number = $product->get_id();
Great catch! Most likely a formatting issue when saving.

Technically, this shouldn't case a fatal error since PHP, similar to C, evaluates an assignment as an expression (thus you can have `$a = $b = $c = 42` which would result in all variables having the same value: `42`). Thus, it is valid code, but not proper. That's why it wasn't an issue in QA-testing.

2024-06-04 16:44 UTC, mntzrr commented on classes/requests/helpers/class-walley-checkout-requests-fees-helper.php
> +		$part_number = ! empty( $product->get_sku() ) ? $product->get_sku() : $part_number = $product->get_id();
It seems like it is called indirectly here:
- [initialize checkout](https://github.com/krokedil/collector-checkout-for-woocommerce/blob/develop-HPOS/classes/requests/checkouts/post/class-walley-checkout-request-initialize-checkout.php#L58)
- [update checkout](https://github.com/krokedil/collector-checkout-for-woocommerce/blob/develop-HPOS/classes/requests/checkouts/put/class-walley-checkout-request-update-checkout.php#L44)

2024-06-05 07:48 UTC, MichaelBengtsson commented on classes/requests/helpers/class-collector-checkout-requests-cart.php
> +		$part_number = ! empty( $product->get_sku() ) ? $product->get_sku() : $part_number = $product->get_id();
The fatal error was more regarding the extra ) i saw, but i cant see it anymore. So maybe i was hallucinating that part 😄 

And yes, the assignment of the `$part_number` again isn't a fatal error, that i know. But it does break WP coding standards of [assignments in conditionals i believe](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/). So should be changed for that reason anyway.

2024-06-05 09:00 UTC, MichaelBengtsson commented on classes/class-walley-part-payment-widget.php
> +		$product = wc_get_product( walley_get_the_ID() );
I am more wondering about [this](https://github.com/krokedil/collector-checkout-for-woocommerce/blob/develop-HPOS/includes/collector-checkout-for-woocommerce-functions.php#L1138-L1144) part of the walley_get_the_ID function. Will that work even for product pages?

2024-06-10 14:59 UTC, mntzrr commented on classes/class-walley-part-payment-widget.php
> +		$product = wc_get_product( walley_get_the_ID() );
Yes, since it calls internally the [WC_Product_Factory::get_product](https://woocommerce.github.io/code-reference/classes/WC-Product-Factory.html#method_get_product) method that will "use global `$post`" to retrieve the product if we pass `false` which is what is happening here.

Maybe it is better to just return `false` directly instead, as the function `walley_get_the_ID` is superfluous?

2024-06-17 06:47 UTC, MichaelBengtsson commented on classes/class-walley-part-payment-widget.php
> +		$product = wc_get_product( walley_get_the_ID() );
@mntzrr or just dont pass anything. It defaults to false anyway, so should pickup the correct product anyway.

2024-06-24 11:11 UTC, MichaelBengtsson approved these changes

2024-06-24 11:11 UTC, merged